### ISSUE TITLE
Trouble installing microtime dependency

### ISSUE THREAD

**Issue by TSFoster** [mdgriffith/elm-markup-cli#1]
Hi,

Congratulations on and thank you for the release of elm-markup v3! I've played around with the examples and it looks great :smiley:.

I'm unable to install this CLI tool, as `microtime` won't install. However, I'm not sure it's necessary anyway? As far as I can tell (from a quick search), it's only used in `timeCheckpoint` in `runners/node/lib.js`, and that function doesn't seem to be being called or exported?

More info on the failed install: despite [this issue](https://github.com/wadey/node-microtime/issues/61) from the `microtime` repo, neither `npm i microtime@2.1.8` nor `npm i microtime@2.1.9` will install. I'm running node v12.3.1 and npm v6.9.0 on macOS 10.14.5.

**Comment by mdgriffith** [comment]
Ah, interesting!  Yeah, I think that can be removed. I was doing some ad-hoc benchmarking at some point, but not anymore.

**Comment by mdgriffith** [comment]
I just published a patch version with that removed.  Thanks for the well described issue!
